name: 'Associative RegEx Issue and PR Labeler'
description: "Labels issues, potentially based on a merged PR, automagically based on their title and body."
author: 'Spartan322'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  title-regex:
    description: 'Is optional if body-regex is defined and the regex to apply to the title.'
    required: false
  body-regex:
    description: 'Is optional if title-regex is defined and the regex to apply to the body.'
    required: false
  find-issue-in-regex:
    description: 'Is optional and determines if it will evaluate issues to label within the selected regex.'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'activity'  
  color: 'blue'
